### ISSUE TITLE
Implement pawn promotion 

### ISSUE THREAD

**Issue by desairudra** [MSTC-DA-IICT/Hacktoberfest24-Chess-Game-Python-Advanced#1]
**Rule for Pawn promotion**:In chess, when a pawn reaches the opponent's back rank (row 8 for white or row 1 for black), it must be promoted to a Queen, Rook, Bishop, or Knight. The player should be prompted to choose which piece they'd like to promote the pawn to.The promotion can be done to Bishop,Knight,Queen or Rook.

**Expected Outcome**:Check for promotion eligibility: When a pawn reaches the back rank, check if the promotion is possible.
Prompt user for piece selection: Once promotion is triggered, prompt the user to choose between a Queen, Rook, Bishop, or Knight.
Replace the pawn with the selected piece: Once the user makes the choice, the pawn should be replaced with the selected piece.
Ensure correct behavior for both white and black pawns: The promotion should work for both white and black pawns when they reach their respective promotion ranks.
Add the promoted piece to the board: The chosen piece should appear on the board in place of the pawn.

**Comment by Abdullah17m** [comment]
Hello @desairudra, can you assign this issue to me, I would like to work on this issue

**Comment by kaushikatgithub** [comment]
I want to work on this issue please assign me

**Comment by desairudra** [comment]
@Abdullah17m and @kaushikatgithub this issue has been assigned to you.

**Comment by kaushikatgithub** [comment]
hey, i want to create PR, but my old PR for issue #4 still not updated, so what should i do. Should create new PR where both issues are combined?
