### ISSUE TITLE
Restructuring the board.

### ISSUE THREAD

**Issue by DivyamThacker** [MSTC-DA-IICT/Hacktoberfest24-Chess-Game-Python-Advanced#11]
1. Give Capital letters to denote White pieces , which is a more intuitive method. 
2. As white's turn is first, It should be the one at the bottom. 
3. Add numbering to the board like g4 to e7 and stuff for easier input giving. (which is also an standard practice in chess)
4. Flip the board when its other person's turn

Please assign this issue to me

**Comment by DivyamThacker** [comment]
Also should I change the notation for consistency? . When making a move for a white's turn we pass 'w' as a parameter , but when we mention the turn of the player , we mention whole "white"

In chessBoard:
![image](https://github.com/user-attachments/assets/daebd18a-b04d-4104-b7f8-7283d393a4ab)

In Game:
![image](https://github.com/user-attachments/assets/b498fce4-e130-4de8-ae3c-0c41d9f78f30)

**Comment by Swayam-Hingu** [comment]
I have updated the original file. Please check it. Also, creating this issue will not count towards Hacktoberfest. Please ask to be assigned to an existing issue that has the Hacktoberfest tag instead.

**Comment by DivyamThacker** [comment]
But what if I have some new Ideas that could really improve the project? Would it not be better that I create a new issue and then if it is a good issue then the moderators can assign the work to me?
