### ISSUE TITLE
queen move invalid

### ISSUE THREAD

**Issue by desairudra** [MSTC-DA-IICT/Hacktoberfest24-Chess-Game-Python-Advanced#15]
We are encountering an error in the current code, as illustrated in the attached screenshot. The issue needs to be investigated and resolved to ensure the functionality of the application.
![erro](https://github.com/user-attachments/assets/d7ba7f96-6696-4594-b0bb-90bfe0cea51c)

**Comment by SanskariWolf** [comment]
Assign it to me

**Comment by kaushikatgithub** [comment]
Hey i want to work on this issue, assign me.
