### ISSUE TITLE
Revamped Chess Game: Modularization and Automated Move Testing

### ISSUE THREAD

**Issue by Abhinav-gh** [MSTC-DA-IICT/Hacktoberfest24-Chess-Game-Python-Advanced#18]
### Description:
This issue outlines some suggested improvements for the chess game codebase aimed at enhancing its functionality and testing capabilities.

### Problems Encountered:
- **Tight Coupling**: The original code is tightly coupled, making it difficult to isolate and test individual components effectively.
- **Manual Testing Limitations**: Testing the game requires manual input for each move, which is time-consuming and prone to errors, especially during regression testing.

### Proposed Improvements:
1. **Modular Code Structure**: Refactor the code into separate modules for the pieces, chessboard, and game logic to enhance maintainability and readability.
2. **Automated Testing**: Introduce support for predefined moves to allow the game to be tested without manual input. This will improve testing efficiency and reduce the chances of human error. The player can play continue to the game after some pre-defined moves have already been made. 

I would appreciate it if this issue could be assigned to me as part of **Hacktoberfest 2024**, and I look forward to contributing further!

**Comment by Swayam-Hingu** [comment]
Hey @Abhinav-gh,
I created an issue for automated testing from the MSTC account and assigned it to you. The modularization has already been completed.
Please take a look and let me know if you have any questions!

**Comment by Swayam-Hingu** [comment]
I am closing this issue

**Comment by Swayam-Hingu** [comment]
Hey @Abhinav-gh, could you please ask to be assigned to the new testing issue?

**Comment by Abhinav-gh** [comment]
Hey @Swayam-Hingu, thank you considering my opinion. I have asked to be assigned to that issue. Thanks!
