### ISSUE TITLE
Check if the king is check free or not

### ISSUE THREAD

**Issue by desairudra** [MSTC-DA-IICT/Hacktoberfest24-Chess-Game-Python-Advanced#2]
**Description**:
After a player makes a move, the game should check if the move results in a "check" on the opponent's king. If the opponent's king is in check, a message should be displayed to inform the players. This feature will enhance the game's interactivity and notify players of critical moments during gameplay.

**Expected Outcome**:
Detect check after every move: After each move, the game must check if the opponent's king is in check.
Notify players: If a check is detected, display a message like: "Check! [Player]'s king is under attack."
Support both players: Ensure check detection works for both white and black players.
Check validation: Only detect check if the king is threatened by any opponent piece, based on valid moves of the attacking piece.

**Comment by kaushikatgithub** [comment]
hey i want to work on this issue, please assign me.

**Comment by desairudra** [comment]
@kaushikatgithub this issue has been assigned to you.If you want to convert project architecture to modular approach you are free to do so

**Comment by kaushikatgithub** [comment]
thank for assigning the issue. Also i think the methods related to check and check-mate should be part of chessboard class instead of game class. This makes sense.
