### ISSUE TITLE
Ask Player for Moves Without Updating the Board

### ISSUE THREAD

**Issue by desairudra** [MSTC-DA-IICT/Hacktoberfest24-Chess-Game-Python-Advanced#3]
**Description**:
The game should continuously ask the player for their desired piece movement without actually updating the chessboard.The goal is to keep asking players for their moves until they decide to exit, without making any changes to the board.

**Expected Outcome**:
 Ask the player where they want to move a specific piece asking about the start coordinates like (x,y) and the end coordinates and piece at (x,y) take input format as starting coordinates,ending corrdinates,pieces to be moved.
Do not update the board.The game should keep asking for moves without reflecting any changes on the board.However after every move make sure to change the player if current turn is of black then next turn will be of white and vice versa.And make sure to make it interactive in every turn it will specify whose turn it is and will specify the input format.No need to validate moves or check for legality simply capture user input.

**Comment by SanskariWolf** [comment]
Can you please assign this issue to me.
