### ISSUE TITLE
Check if player move is valid or not

### ISSUE THREAD

**Issue by desairudra** [MSTC-DA-IICT/Hacktoberfest24-Chess-Game-Python-Advanced#4]
**Description**
After every move by a player in a chess game, the move must be validated to ensure it adheres to the official chess rules before updating the game state.

**Requirements**
Each piece (king, queen, rook, bishop, knight, pawn) must only be able to move in accordance with chess rules.Also if move is valid then you need to make changes about updating the final location of piece and making it's previous initial or start location empty.And after updating the board if possible you need to print the current chess board.if the move is invalid then you will not swap player and keep asking the same player until valid move is made.

**Comment by kaushikatgithub** [comment]
I want to work on this issue please assign me.

**Comment by desairudra** [comment]
@kaushikatgithub this issue has been assigned to you

**Comment by kaushikatgithub** [comment]
can i modify function names and number of arguments?

**Comment by desairudra** [comment]
Please try to keep same function name.Number of arguments can be changed by you if required.

**Comment by kaushikatgithub** [comment]
okay thanks, also i can add other methods if required ?

**Comment by desairudra** [comment]
If from methods you mean function that are part of class,then Yes.else if you mean creating other methods rather than updating the given function then no.

**Comment by kaushikatgithub** [comment]
Hey, the code that is given has called the upper half of the board as the white piece side and lower half as the black piece half but in reality it should be opposite.
