### ISSUE TITLE
Enhancement: Create a GUI for Chess Board Representation using Pygame

### ISSUE THREAD

**Issue by SanskariWolf** [MSTC-DA-IICT/Hacktoberfest24-Chess-Game-Python-Advanced#7]
**Description**
I would like to propose an enhancement to the project by creating a graphical user interface (GUI) for displaying the chess board using Pygame. While the current implementation successfully prints the chess board in the terminal, a GUI would greatly improve user interaction and accessibility.

**Expected outcome**
The expected outcome is a fully functional Pygame application that displays the chess board visually, with each piece represented by corresponding images or symbols.

**Comment by SanskariWolf** [comment]
I would like this issue to be assigned to me under Hacktoberfest2024

**Comment by desairudra** [comment]
We had look into your idea.We liked your idea but this repo is highly focuses on making interactive and user friendly console base chess.please kindly try to complete issues wise functionality
